name: Regenerate Gradle Wrapper

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Download Gradle 8.8
        run: wget https://services.gradle.org/distributions/gradle-8.8-bin.zip

      - name: Unzip Gradle
        run: unzip gradle-8.8-bin.zip

      - name: Copy Gradle Wrapper
        run: cp gradle-8.8/bin/gradle-wrapper.jar
